checksumBehavior: ignore

compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTelemetry: false

nmSelfReferences: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.3.cjs
