checksumBehavior: ignore

compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTelemetry: false

nmSelfReferences: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
